### create product
POST http://localhost:8091/product
Content-Type: application/json

{
    "name": "Product max",
    "description": "Product 1 description",
    "price": 1001
}


### get all product
GET http://localhost:8091/product/all



### get product
GET http://localhost:8091/product/657025fb88b76633e9f25ab9

